### ISSUE TITLE
Xbox One Support

### ISSUE THREAD

**Issue by smoak** [ags131/node-ld#1]
I don't believe this supports the xbox one version of the toy pad. At least for me the productId is 0x0141 not 0x0241. I've modified the `transports/libusb.js` file to use 0x0141 in my case, but none of the demos work. I suspect the protocol is different :cry:

**Comment by ags131** [comment]
The Xbox version of the portal has extra auth for use with the xbox, not sure if it can be used from PC. What OS you using?

**Comment by smoak** [comment]
I'm using Linux

**Comment by ags131** [comment]
Does running toypadDemo.js give you any error output?

**Comment by smoak** [comment]
No errors. All I see are the REQs sent to the pad, but the pad is not lighting up.

**Comment by ags131** [comment]
Hmm, so it is loading the endpoints. Any RESs coming back? Or just the REQs alone?

**Comment by smoak** [comment]
No RESs in the output, only REQs.

**Comment by ags131** [comment]
Hmm, I have no ideas. :/ I'll add a note to the Readme noting that XBOX versions aren't currently supported, If I can catch the xbox starter pack for cheap one day I may pick one up and see what I can figure out.

**Comment by smoak** [comment]
What would I need to figure this out on my own? Do I need special hardware or anything (e.g. a usb sniffer)?

**Comment by ags131** [comment]
I'm not actually sure, Xbox accessories include an extra chip that auths with the Xbox, AFAIK, that auth sequence hasn't been reverse engineered

**Comment by smoak** [comment]
Interesting. I'd love to figure this out but don't really know where to start (new at this hardware usb stuff). Do you have any suggestions?

**Comment by ags131** [comment]
I used a microcontroller to sniff the LD portals data streams, but that USB auth is at a much lower level, You would probably need a full USB mitm device.

**Comment by ags131** [comment]
Closing as this doesn't look like it will be possible in the near future.
