### ISSUE TITLE
gulp error on npm install

### ISSUE THREAD

**Issue by britannia2** [ags131/node-ld#16]
I wanted to install node-ld from scratch on a new device.
Therfore I more or less followed your instruction in the installation section of the Readme.
I got the latest sources of node-ld in a corresponding folder with that name and run npm install.
Unfortunately gulp is throwing an error.

Please find the npm-debug.log attached
[npm-debug.zip](https://github.com/ags131/node-ld/files/683338/npm-debug.zip)

The interesting thing is: If I run 'npm install node-ld' it runs w/o any error. But it seems there is no compilation of node-ld or execution of gulp in that case.

**Comment by ags131** [comment]
Looks like you don't have gulp installed, you can install it by running `npm install -g gulp-cli`
The npm version doesn't require it as it is precompiled before publish

**Comment by britannia2** [comment]
I did a non-global 'npm install gulp-cli', or is it required globaly?

Same as before:

[22:38:47] Using gulpfile ~/node-ld/gulpfile.js
[22:38:47] Starting 'es6'...
[22:39:13] Finished 'es6' after 26 s
[22:39:13] Starting 'node'...
[22:39:13] Finished 'node' after 213 μs
[22:39:13] Starting 'bundle'...
events.js:160
      throw er; // Unhandled 'error' event

**Comment by ags131** [comment]
using the local works too, thats a wierd error, looks like its inside the browserify step. I can't tell much more than that though, its working fine here when I test.

**Comment by britannia2** [comment]
Is this step important ? So far everything seems to work.
The only obvious difference I can see is that these files are missing:

build\browser\node-ld.js
build\browser\node-ld.min.js

**Comment by ags131** [comment]
Ahh, should be able to just remove that line completely, looks like the `debug` package improved their browserify support, originally that was needed to get it to build.
