### ISSUE TITLE
Remaining questions with respect to the commands

### ISSUE THREAD

**Issue by britannia2** [ags131/node-ld#18]
Meanwhile I have a quite good understanding of all the commands and events. But few ones are still not very clear to me.

What are these commands for?
CMD_SEED  : 0xB1 -> what is the seed used for and what is the 
CMD_CHAL  : 0xB3 -> looks like a 'still alive ?' request
CMD_LEDSQ : 0xFF -> gave it a try, but nothing happend, don't know the correct payload

**Comment by ags131** [comment]
Seed and chal are the PRNG generator, it seeds it then verifies it. Used to authenticate the portal. Without it the console resets the portal

**Comment by ags131** [comment]
CMD_LEDSQ : 0xFF no idea, probably a leftover
