### ISSUE TITLE
Example of writing to NFC Chip

### ISSUE THREAD

**Issue by withgallantry** [ags131/node-ld#2]
Hi, I'm not even sure if it's possible but I was wondering if you managed to successfully write to a chip. I had a good read through yours and other peoples sources but couldn't find the necessary information on how to write a 130 length buffer to a chip using it. 
The NPM library USB is currently having issues so I couldn't run every demo.

**Comment by atkinchris** [comment]
Are you trying to write to genuine tag or a generic 213, and via the portal or RFID writer/Android?

**Comment by withgallantry** [comment]
Writing to a genuine tag and via the portal. I'm hoping to clone a vehicle using the toypad alone as I believe the characters are protected via a password.

**Comment by ags131** [comment]
Using the portal its as easy as doing a READ on pages 24-26 and a WRITE on the new tag. 
The PWD algo is known, just look in commit history. ;)
Characters have those pages encrypted with a key generated from UID + some magic, I have plans to add that code, but haven't had a chance yet. Vehicles can be copied straight up. Page 25 is the vehicle ID, page 23 and 26 are the upgrade values
Using the PWD gen, you can even use generic 213 tags, just have to set the PWD from a regular writer or android.

**Comment by withgallantry** [comment]
Cheers ags131! I found that password magic after I'd posted. Brilliant work. Can't wait for the the character pages code too!!
