### ISSUE TITLE
Jumping back to parent directory

### ISSUE THREAD

**Issue by gedi223** [ags131/node-ld#24]
I discovered your repository and through here and the proxmark community have learned how to back up my children's lego dimension characters to ntag213.  Unfortunately the android app does not work as my device is on 4.1.2

I have downloaded the github and installed nodejs 4.2 and installed using npm install in the node-ld directory. When using the node samples\characters.js  I get the following error:

C:\edbackup\green\Test>node samples\characters.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\edbackup\green\data\character
map.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (C:\edbackup\green\Test\samples\characters.js:14:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)

C:\edbackup\green\Test>

It appears that it is looking for the charactermap.json in the parent directory of c:\edbackup\green instead of c:\edbackup\green\Test

When I copy the contents of c:\edbackup\green\Test to C:\edbackup\green and then run node samples\characters.js in the c:\edbackup\green\test directory, it works and outputs the UID request and then the character list

I also noticed I get a discrepency in the ouput

I borrowed a UID from proxmark post 0489717A333580

When I put it in the character.js file I get

[acb9a6f4] [c41660b6] ... [660d01d8] Chell

However, on the post, the OP lists 
A798B47F page 36
755D0DBF Page 37
for chell
referencing your http://ldcharcrypto.ags131.com/ site no longer available

The pwd from characters.js and pwdgen.js and bettse site all agree for 660d01d8

Thank you for your time

**Comment by ags131** [comment]
The directory issue is mostly due to me always running the scripts from inside the sample folder IIRC, 
Looking at that post, it looks like he was writing a vehicle, page 36 and 37 will match on all tags for vehicles, but is unique per tag for characters.  I'll try to get the ldcahrcrypto site back up, it was just charCryptoExample.js in an html page though, so should give the same results.

**Comment by gedi223** [comment]
Thank you for the quick reply.  Now I must wait 2 weeks to get my tags from China so that I can start the long process of making copies of the Figures and vehicles.  In the meantime, I have Olfans wonderful explanation on vehicle upgrades to read through and learn how to write vehicles and characters with NFC Pro tools
