### ISSUE TITLE
Charactermap.json end of line , 

### ISSUE THREAD

**Issue by gedi223** [ags131/node-ld#25]
Looks like in the updated Charactermap.json you left the , after line 69 

{        "id": 68,         "name":"Chase McCain", "world":"LEGO City" },

Will give the following error:

C:\Temp2\node-ld-master>node samples\characters.js
undefined:70
]
^

SyntaxError: Unexpected token ]
    at Object.parse (native)
    at Object.<anonymous> (C:\Temp2\node-ld-master\samples\characters.js:14:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by crstofer** [comment]
Thanks will update

**Comment by ags131** [comment]
Should be fixed in  97714cb

**Comment by gedi223** [comment]
Sorry to keep "bugging" you. But I am amazed at the work you have done on this. I have finally figured out how tea is used to generate the pwd. But am still working on following the character generation for pages 36 and 37.  It has been 15 years since I've touched any coding and your work has been excellent read.

**Comment by gedi223** [comment]
I see you got the remaining ids as well, was just about to send those to you.

**Comment by ags131** [comment]
No problem, I don't mind. the pwd itself doesn't use TEA, but does use the same algorithm used for the encryption key generation for the characters. The character id is then encrypted with that key for the token.
