### ISSUE TITLE
Writing Character Tags

### ISSUE THREAD

**Issue by withgallantry** [ags131/node-ld#3]
Hi @ags131 
Thanks for adding the character code. Just wanted to double check my findings. You can't write a character to a vehicle tag or overwrite a character tag can you? I can't manage to do either using just the lego dimensions portal.
I'm guessing I need an RFID writer. Is it a simple case of turning the byte in page 0x27 into 00 instead of 1 for a character? (my character starts at page 0x25)

**Comment by ags131** [comment]
If I'm not mistaken 0x27 is actually locked readonly, characters also have more locked pages, it wouldn't surprise me if those are 0x25 & 0x26, I haven't looked at the lock bits lately so don't remember the exact ones. Vehicles however, can be overwritten very easily with other vehicles. 0x24 & 0x26 is upgrade data with 0x25 being vehicle ID (See the vehicle json file for a list of most of the IDs)

**Comment by withgallantry** [comment]
I thought so. I couldn't get a character tag to work on a a vehicle tag. I'm going to try and create one on a blank NTAG2013 tomorrow as I've not got my reader currently. I'll update when I've tried it. 
I managed to get the vehicles updating easily. Thanks again for all the hard work.

**Comment by atkinchris** [comment]
Looking at dumps, the static lock bytes for both characters and vehicles are `1F 00` (BL CC, 9-4, 15-10 & L CC, 4). However, the dynamic lock bytes for vehicles are `60 08 3F`, while characters have `60 0C 3F`, which additionally locks pages 36 & 37, that contain character data. Both tags lock pages 38 & 39, so you can't change the tag type byte.

I don't fully understand dynamic lock bits on these tags to know if the lock is permanent.

**Comment by ags131** [comment]
You can only write dynamic lock bits, any further writes are 'or'ed with the existing value.

**Comment by withgallantry** [comment]
Would cloning an existing character disc onto an NTAG213 then updating the neccrssary pages work? Or would cloning clone the locked bytes? I'm fairly new to NFC so I'm not sure if cloning just clones the data or the protection also.

**Comment by ags131** [comment]
You should be fine as long as you only write the data pages. You will have to set the PWD calculated from the new UID using something other than the portal (Such as an android phone). the Character ID would need encrypted with the new key derived from UID

**Comment by withgallantry** [comment]
That's what I was thinking, shouldn't be too difficult.
Would you use something other than the portal to clone an existing character disc onto an NTAG213 then update the PWD and encrypted pages  0x25 & 0x26 using the new UID. That should be all that's needed?

Or, could I just write pages 0x25 & 0x26 data onto a blank disc after I have set the PWD and used the UID to encrypt the data for 0x25 and 0x26.

Just trying to work out what the bare minimum for a character required is.

**Comment by ags131** [comment]
I think you have to set the PWD first, but yes, 0x25 and 0x26 is all thats needed on a character (With 0x27 being 0) 
The portal isn't able to set the PWD, so that has to be done seperately, but after that point the portal would be easiest to use since you can abuse the existing functions for the encryption ;)

**Comment by withgallantry** [comment]
Brilliant. Thanks for the info. I've got some NTAG213 arriving tomorrow so I'll give it a go. Brilliant work on the PWD and encryption.

**Comment by ags131** [comment]
Technically, the game only ever sees the UID in the placement events. The game ignores UID
When a token is placed it does the following:
0. Portal calculates PWD and auths token
1. Game reads 0x24 (Returns 4 pages so 0x24,0x25,0x26,0x27)
2. if(0x27 == 0) process character otherwise its vehicle (0x24,0x25,0x26 are IGNORED on characters)
3a. if character do D4 to get ID
    portal decrypts token using UID key, then encrypts using static TEA key
3b. if vehicle 0x25 == ID and 0x24,0x26 are upgrades (uint64) (No encryption)

Those 4 pages are the only important ones on the tag, the rest are ignored for gameplay

**Comment by withgallantry** [comment]
That makes sense. Only thing I'm not sure on is D4 - is that a memory address?
So far I've seen the encrypted ID + uID on pages 0x25 and 0x26.

**Comment by ags131** [comment]
0xD4 is part of the USB protocol, its the command ID
The game sends a D4 packet containing a nfc index to read, the portal decrypts the character data on that tag, reencrypts it with the static key, and sends it back to the game.

**Comment by ags131** [comment]
Before we knew the decryption for the tags, I spoofed the data by encrypting my own ID and sending it to the game, thats why D4 in ToyPadEmu is so wonky

**Comment by withgallantry** [comment]
I'm with you now. Does it use TEA also to encrypt the data on the tag, with a key comprised using the UID? 
Much easier to spoof the data to the game using the static key :)

**Comment by ags131** [comment]
Yes, its a key derived from the UID used with TEA on the tag. see CharCrypto for how that key is actually generated and how the data is stored. (charid is saved twice into a 8 byte chunk then encrypted ex: [01 00 00 00 01 00 00 00])

**Comment by withgallantry** [comment]
Thanks @ags131. The genKey function must be the function that runs on the toypads hardware. I've learnt so much from this conversation.

**Comment by withgallantry** [comment]
Any recommendations for software? struggling to find anything to write the PWD and PACK pages. I found one but I don't trust it as it's returning bytes different to what the toypad is saying on pages 24,25 and 26. Any operating system (inc android) is fine :)

**Comment by ags131** [comment]
I have used this app with other tags, haven't tried with ld since PWD gen
was discovered, but should work fine.
https://play.google.com/store/apps/details?id=com.wakdev.nfctools.pro

**Comment by withgallantry** [comment]
Thanks. I gave that a go and it worked. I've also finally found a way to use the acs acr122u from my mac to write the tags now without using the toypad.

**Comment by matthewbullweb** [comment]
Got NFC Tools pro app and can't see pages. Only a basic text string is visable. Wondering how to use it for vehicle id swapping.

**Comment by dmfp87** [comment]
Has anyone actually successfully written characters they don't have onto a vehicle tag or new blank tag and can they tell me how to do it? I have no experience with all this NFC stuff, but I downloaded NFC Tools.
