### ISSUE TITLE
How do I use this properly?

### ISSUE THREAD

**Issue by ProgrammingWolf** [ags131/node-ld#7]
Sorry to bother anybody but, i ran the  toypadDemo.js, and it gave me an error saying there was a syntax error on line 8 
character 23 
code 800A03EA 
source Microsoft JScript compilation error.

Sorry again for being stupid.

**Comment by ags131** [comment]
It has to be run using node.js on the commandline, doubleclicking the js file just tries running the windows JS environment.
Node.js version 4.1 or higher is recommended https://nodejs.org/
from a command prompt in the node-ld folder:
npm install (This installs any dependencies needed)
node samples\toypadDemo.js (Runs the demo)

**Comment by ProgrammingWolf** [comment]
thank you

**Comment by ProgrammingWolf** [comment]
I am sorry but when i type "node samples\toyboxDemo.js"  I get the error of
Error: Cannot find module 'node-hid'
    at Function.Module.resolveFilename (module.js:399:15)
    at Function.Module.load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19
    at Object.<anonymous> (C:\Users\UsernameHere\Desktop\node-ld-master\transports\hid.js:6:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12) 
    at Module.require (module.js:367:17)

**Comment by ags131** [comment]
the `npm install` command should install that

**Comment by ProgrammingWolf** [comment]
when i do it gives me errors and is only able to do some of it

**Comment by ags131** [comment]
what does node -v return?

**Comment by ProgrammingWolf** [comment]
5.5.0

**Comment by ProgrammingWolf** [comment]
![2016-01-28 1](https://cloud.githubusercontent.com/assets/4752804/12650403/51561dc2-c5a8-11e5-8476-ad24900011e6.png)

**Comment by ProgrammingWolf** [comment]
![2016-01-28 1](https://cloud.githubusercontent.com/assets/4752804/12650460/901c7060-c5a8-11e5-8eee-0dec9fe89f31.png)

**Comment by ags131** [comment]
Try with node 4.2, it doesn't look like node-hid has prebuild binaries for 5.5

**Comment by ags131** [comment]
You will need to uninstall 5.5 before installing 4.2

**Comment by ProgrammingWolf** [comment]
Ok

**Comment by ProgrammingWolf** [comment]
same error

**Comment by ProgrammingWolf** [comment]
forgot to do npm install

**Comment by ProgrammingWolf** [comment]
![2016-01-28 2](https://cloud.githubusercontent.com/assets/4752804/12650879/271ae1b2-c5aa-11e5-964a-2f8e602e1239.png)

**Comment by atkinchris** [comment]
Please can you report what `npm -v` shows?

**Comment by ProgrammingWolf** [comment]
it says for some reason 2.14.12 when i installed 4.2.6

**Comment by ProgrammingWolf** [comment]
now i am confused

**Comment by ags131** [comment]
npm is the package manager that comes with node, its supposed to be a different version

**Comment by ags131** [comment]
delete the node_modules folder (To ensure a clean run) and run `npm install` again, as long as it doesnt throw ERROR, you should be able to run toypadDemo

**Comment by ProgrammingWolf** [comment]
the node_modules in the node-ld folder?

**Comment by ags131** [comment]
yes

**Comment by ProgrammingWolf** [comment]
![2016-01-28 3](https://cloud.githubusercontent.com/assets/4752804/12651521/7fae751c-c5ac-11e5-9503-f65a4e65deac.png)

**Comment by ProgrammingWolf** [comment]
I deleted the folder, ran it, got this error, reinstalled the node-ld-master folder, ran it and still this error

**Comment by ags131** [comment]
Thats not an error, its just a warning. `node samples/toypadDemo.js` should work now

**Comment by ProgrammingWolf** [comment]
oh ok

**Comment by ProgrammingWolf** [comment]
gave me an error saying cannot write to the HID device

**Comment by ags131** [comment]
Try it again, I get that error sometimes and it usually works after a couple tries

**Comment by ProgrammingWolf** [comment]
cool.

**Comment by ProgrammingWolf** [comment]
so now how do i edit the toy tags and stuff?

**Comment by ProgrammingWolf** [comment]
also how do i terminate the program without closing the command prompt
sorry i am really a huge noob

**Comment by ags131** [comment]
Mostly you would need to write your own code for editing, this is mostly a library that makes it easier to work with the raw data.
Ctrl-C should terminate the program

**Comment by ProgrammingWolf** [comment]
thank you

**Comment by ProgrammingWolf** [comment]
sorry to bother again but, on the newVehicle program what is "var out1 = new Buffer ([0x8E, 0x04, 0x00, 0x00])" and how do i change it to what i want with the data given in the token map

**Comment by ags131** [comment]
out1.writeUInt32LE(1234) after that var line would update that buffer with token id 1234

**Comment by ProgrammingWolf** [comment]
k thanks

**Comment by ProgrammingWolf** [comment]
it gave me an unexpected token var error

**Comment by ProgrammingWolf** [comment]
Has anybody even found out how to edit characters?

**Comment by ProgrammingWolf** [comment]
Vehicles are easy but characters seem like there is no way to break through them

**Comment by atkinchris** [comment]
You cannot edit character tags; they are permanently locked.

**Comment by ProgrammingWolf** [comment]
oh

**Comment by ProgrammingWolf** [comment]
but people have been searching for a pwd gen to get through havent they?

**Comment by ags131** [comment]
PWD only works if the lock bits haven't been set, on characters they are set

**Comment by atkinchris** [comment]
No password will help. Character tags are permanently locked at a hardware level; they cannot be rewritten. Vehicle tags are also permanently locked at a hardware level to be a vehicle tag.

**Comment by ProgrammingWolf** [comment]
so, there will be no way to ever write to the character tags?

**Comment by atkinchris** [comment]
No. They are permanently locked on the tag itself.

**Comment by ProgrammingWolf** [comment]
oh well. Thanks

**Comment by ProgrammingWolf** [comment]
I was spending the  past hour figuring that out lol
